name: Update data

on:
  schedule:
    # We'll run this weekly
    - cron:  '0 12 * * 1'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: ols-program-paper
          #environment-file: environment.yml

      - shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show

      - name: Update data
        shell: bash -el {0}
        run: |
          cd src
          for i in {extract_data_from_website.ipynb}; do
            jupyter nbconvert "$i" --to python --output "$i.py"
            python "$i.py"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Commit files
        shell: bash -el {0}
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "github-actions[bot]"
          git add data
          git commit -m "Updated data ($(date -I))" || true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}
